Pages/Admin/Shoes/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nevada.Data;
using Nevada.Models;
using Nevada.Models.ViewModel;

namespace Nevada.Pages.Admin.Shoes
{
    public class AddModel : PageModel
    {
        [BindProperty]
        public AddShoes AddShoesRequest { get; set; }

        private readonly ApplicationDbContext _context;
        public AddModel(ApplicationDbContext context)
        {
            this._context = context;
        }

        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            var shoe = new ShoesModel()
            {
                ShoeName = AddShoesRequest.ShoeName,
                Price = AddShoesRequest.Price,
                ImageTitle = AddShoesRequest.ImageTitle,
                OutOfStock = AddShoesRequest.OutOfStock,
                Property = AddShoesRequest.Property,
                Size = AddShoesRequest.Size
            };
            _context.Shoes.Add(shoe);
            _context.SaveChanges();

            return RedirectToPage("/Shoe");
        }

    }
}

Pages/Admin/Shoes/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nevada.Data;
using Nevada.Models;


namespace Nevada.Pages.Admin.Shoes
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext context;

        [BindProperty]
        public ShoesModel Shoe { get; set; }

        public EditModel(ApplicationDbContext context)
        {
            this.context = context;
        }
        public void OnGet(Guid id)
        {
            Shoe = context.Shoes.Find(id);
        }
        public IActionResult OnPostEdit()
        {
            var existingShoe = context.Shoes.Find(Shoe.Id);
            if (existingShoe != null)
            {
                existingShoe.Property = Shoe.Property;
                existingShoe.Price = Shoe.Price;
                existingShoe.OutOfStock = Shoe.OutOfStock;
                existingShoe.Size = Shoe.Size;
                existingShoe.ShoeName = Shoe.ShoeName;
                existingShoe.ImageTitle = Shoe.ImageTitle;
            }
            context.SaveChanges();
            return RedirectToPage("/Admin/Shoes/List");
        }
        public IActionResult OnPostDelete(int id)
        {
            var existingShoe = context.Shoes.Find(Shoe.Id);
            if (existingShoe != null)
            {
                context.Shoes.Remove(existingShoe);
            }
            context.SaveChanges();
            return RedirectToPage("/Admin/Shoes/List");
        }

    }
}

Pages/Admin/Shoes/EditOrders.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nevada.Data;
using Nevada.Models;

namespace Nevada.Pages.Admin.Shoes
{
    public class EditOrdersModel : PageModel
    {
        [BindProperty]
        public ShoeOrder Order { get; set; }
        private readonly ApplicationDbContext context;

        public EditOrdersModel(ApplicationDbContext context)
        {
            this.context = context;
        }

        public void OnGet(Guid id)
        {
            Order = context.ShoeOrders.Find(id);
        }
        public IActionResult OnPostEdit()
        {
            var existingOrder = context.ShoeOrders.Find(Order.Id);
            if (existingOrder != null)
            {
                existingOrder.ShoesModelId = Order.ShoesModelId;
                existingOrder.CustomerAddress = Order.CustomerAddress;
                existingOrder.Price = Order.Price;
                existingOrder.CustomerPhone = Order.CustomerPhone;
                existingOrder.CustomerName = Order.CustomerName;
                existingOrder.ShoeName = Order.ShoeName;
                existingOrder.Delivered = Order.Delivered;
            }
            context.SaveChanges();
            return RedirectToPage("/Admin/Shoes/Orders");
        }
        public IActionResult OnPostDelete(int id)
        {
            var existingOrder = context.ShoeOrders.Find(Order.Id);
            if (existingOrder != null)
            {
                context.ShoeOrders.Remove(existingOrder);
            }
            context.SaveChanges();
            return RedirectToPage("/Admin/Shoes/Orders");
        }
    }
}

Pages/Admin/Shoes/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nevada.Data;
using Nevada.Models;

namespace Nevada.Pages.Admin.Shoes
{
    public class ListModel : PageModel
    {
        private readonly ApplicationDbContext context;

        public List<ShoesModel> Shoes { get; set; }

        public ListModel(ApplicationDbContext context)
        {
            this.context = context;
        }
        public void OnGet()
        {
            Shoes = context.Shoes.ToList();
        }
    }
}

Pages/Admin/Shoes/Orders.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nevada.Data;
using Nevada.Models;

namespace Nevada.Pages.Admin.Shoes
{
    public class OrdersModel : PageModel
    {
        public List<ShoeOrder> ShoeOrders {get; set;} 

        private readonly ApplicationDbContext _context;
        public OrdersModel(ApplicationDbContext context)
        {
            _context = context;
        }
        public void OnGet()
        {
            ShoeOrders = _context.ShoeOrders.ToList();
        }
    }
}

Pages/Orders.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nevada.Data;
using Nevada.Models;

namespace Nevada.Pages
{
    public class OrdersModel : PageModel
    {
        public List<ShoeOrder> ShoeOrders = new List<ShoeOrder>();

        private readonly ApplicationDbContext _context;
        public OrdersModel(ApplicationDbContext context)
        {
            _context= context;
        }
        public void OnGet()
        {
            ShoeOrders = _context.ShoeOrders.ToList();  
        }
    }
}

Pages/Shoe.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nevada.Models;

namespace Nevada.Pages
{
    public class ShoeModel : PageModel
    {
        public List<ShoesModel> ShoeDB = new List<ShoesModel>()
        {
            new ShoesModel(){ImageTitle="AirJordan1MidSe",ShoeName="AirJordan1MidSe", Price=50},
            new ShoesModel(){ImageTitle="NikeAirForce1High",ShoeName="NikeAirForce1High", Price=50},
            new ShoesModel(){ImageTitle="NikeAirMax90E",ShoeName="NikeAirMax90E", Price=50 , },
            new ShoesModel(){ImageTitle="NikeMetcon8",ShoeName="NikeMetcon8", Price=50 , },
            new ShoesModel(){ImageTitle="NikePegasus39Premium",ShoeName="NikePegasus39Premium", Price=50}
        };
        public void OnGet()
        {
        }
    }
}

Pages/Admin/Shoes/Add.cshtml
@page
@model Nevada.Pages.Admin.Shoes.AddModel
@{
}
<div class="bg-secondary bg-opacity-10 mb-5">
    <div class="container">
        <h1>Add Shoes</h1>
    </div>
</div>

<div class="container mb-5">
    <form method="post">
        <div class="mb-3">
            <label for="shoeName" class="form-label">Shoe Name</label>
            <input type="text" class="form-control" id="shoeName" asp-for="AddShoesRequest.ShoeName" />
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="text" class="form-control" id="price" asp-for="AddShoesRequest.Price" />
        </div>
        <div class="mb-3">
            <label for="size" class="form-label">Size</label>
            <input type="number" class="form-control" id="size" asp-for="AddShoesRequest.Size" />
        </div>
        <div class="mb-3">
            <label for="property" class="form-label">Property</label>
            <textarea class="form-control" id="property" asp-for="AddShoesRequest.Property"></textarea>
        </div>
        <div class="mb-3">
            <label for="imageTitle" class="form-label">Image Title</label>
            <input type="text" class="form-control" id="imageTitle" asp-for="AddShoesRequest.ImageTitle" />
        </div>
        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" id="outOfStock" asp-for="AddShoesRequest.OutOfStock">
            <label class="form-check-label" for="outOfStock">
                Out of stock
            </label>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
    </form>
</div>

Pages/Admin/Shoes/Edit.cshtml
@page "{id:Guid}"
@model Nevada.Pages.Admin.Shoes.EditModel
@{
}
<div class="bg-secondary bg-opacity-10 mb-5">
    <div class="container">
        <h1>Edit Shoes</h1>
    </div>
</div>

<div class="container mb-5">
    <form method="post">
        <div class="mb-3">
            <label for="id" class="form-label">Id</label>
            <input type="text" class="form-control" id="id" asp-for="Shoe.Id" readonly />
        </div>
        <div class="mb-3">
            <label for="shoeName" class="form-label">Shoe Name</label>
            <input type="text" class="form-control" id="shoeName" asp-for="Shoe.ShoeName" />
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="text" class="form-control" id="price" asp-for="Shoe.Price" />
        </div>
        <div class="mb-3">
            <label for="size" class="form-label">Size</label>
            <input type="number" class="form-control" id="size" asp-for="Shoe.Size" />
        </div>
        <div class="mb-3">
            <label for="property" class="form-label">Property</label>
            <textarea class="form-control" id="property" asp-for="Shoe.Property"></textarea>
        </div>
        <div class="mb-3">
            <label for="imageTitle" class="form-label">Image Title</label>
            <input type="text" class="form-control" id="imageTitle" asp-for="Shoe.ImageTitle" />
        </div>
        <div class="mb-3 form-check">
            <input class="form-check-input" type="checkbox" id="outOfStock" asp-for="Shoe.OutOfStock">
            <label class="form-check-label" for="outOfStock">
                Out of stock
            </label>
        </div>
        <div class="mb-3 d-flex justify-content-between">
            <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Submit</button>
            <button class="btn btn-danger" type="submit" asp-page-handler="Delete">Delete</button>
        </div>
    </form>
</div>

Pages/Admin/Shoes/EditOrders.cshtml
@page "{id:Guid}"
@model Nevada.Pages.Admin.Shoes.EditOrdersModel
@{
}
<div class="bg-secondary bg-opacity-10 mb-5">
<div class="container">
    <h1>Edit Order</h1>
</div>
</div>



<div class="container mb-5">
    <form method="post">
        <div class="mb-3">
            <label for="id" class="form-label">Id</label>
            <input type="text" class="form-control" id="id" asp-for="Order.Id" readonly/>
        </div>
        <div class="mb-3">
            <label for="ShoesModelId" class="form-label">ShoesModelId</label>
            <input type="text" class="form-control" id="ShoesModelId" asp-for="Order.ShoesModelId" readonly />
        </div>
        <div class="mb-3">
            <label for="shoeName" class="form-label">Shoe Name</label>
            <input type="text" class="form-control" id="shoeName" asp-for="Order.ShoeName" readonly />
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="text" class="form-control" id="price" asp-for="Order.Price" readonly />
        </div>
        <div class="mb-3">
            <label for="customerName" class="form-label">Customer Name</label>
            <input type="text" class="form-control" id="customerName" asp-for="Order.CustomerName" readonly />
        </div>
        <div class="mb-3">
            <label for="customerAddress" class="form-label">Customer Address</label>
            <input type="text" class="form-control" id="customerAddress" asp-for="Order.CustomerAddress" readonly />
        </div>
        <div class="mb-3">
            <label for="customerPhone" class="form-label">Customer Phone Title</label>
            <input type="number" class="form-control" id="customerPhone" asp-for="Order.CustomerPhone" readonly />
        </div>
        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" id="delivered" asp-for="Order.Delivered" name="Order.Delivered">
            <label class="form-check-label" for="delivered">
                Delivered
            </label>
        </div>
        <div class="mb-3 d-flex justify-content-between">
            <button class="btn btn-primary" type="submit" asp-page-handler="Edit">Submit</button>
            <button class="btn btn-danger" type="submit" asp-page-handler="Delete">Delete</button>
        </div>
    </form>
</div>

Pages/Admin/Shoes/List.cshtml
@page
@model Nevada.Pages.Admin.Shoes.ListModel
@{
}
<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Shoes</h1>
    </div>
</div>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <td>Id</td>
                <td>ShoeName</td>
                <td> </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var shoe in Model.Shoes)
            {
                <tr>
                    <td>@shoe.Id</td>
                    <td>@shoe.ShoeName</td>
                    <td><a href="/Admin/Shoes/Edit/@shoe.Id">View</a></td>
                </tr>
            }

        </tbody>
    </table>
</div>

Pages/Admin/Shoes/Orders.cshtml
@page
@model Nevada.Pages.Admin.Shoes.OrdersModel
@{
}

<div class="bg-secondary bg-opacity-10 py-2 mb-5">
    <div class="container">
        <h1>Orders</h1>
    </div>
</div>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <td>Id</td>
                <td>Shoe Name</td>
                <td>Price</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model.ShoeOrders)
            {
                <tr>
                    <td>@order.Id</td>
                    <td>@order.ShoeName</td>
                    <td>@order.Price $</td>
                    <td><a href="/Admin/Shoes/EditOrders/@order.Id">View</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>